### ISSUE TITLE
FR: Asset field support

### ISSUE THREAD

**Issue by turnstylerj** [digitalpulsebe/craft-multi-translator#12]
We use a plain text field on Asset field layouts for Alternative Text. It would be great if we could batch-translate assets in the same way we can translate entries with this plugin.

**Comment by JodebaDigitalPulse** [comment]
Hi @turnstylerj , thank you for your suggestion. We definitely need to provide this ability, I'll keep you posted!

**Comment by JodebaDigitalPulse** [comment]
Hi @turnstylerj, try updating the plugin to the latest version for translating assets.

**Comment by turnstylerj** [comment]
Awesome, thanks for the quick update!
