### ISSUE TITLE
FR: Adding OpenAI Model gpt-4o

### ISSUE THREAD

**Issue by HigumaSan4050** [digitalpulsebe/craft-multi-translator#14]
Please add the new model GPT-4o for the possible OpenAI models. This is much cheaper than the conventional GPT-4 model.
[pricing](https://openai.com/api/pricing/)

**Comment by JodebaDigitalPulse** [comment]
Hi @HigumaSan4050 , great suggestion, I added more models in the settings (update the plugin to access the new options). But I think the OpenAI method is less reliable than DeepL or Google Translate in my experience.
