### ISSUE TITLE
translations for field "title" and "alt"

### ISSUE THREAD

**Issue by HigumaSan4050** [digitalpulsebe/craft-multi-translator#15]
All Elements:
When translating, the plugin does not check whether the title field should actually be translated or not. It is always translated if filled.

Assets:
In addition, the "alt" field is not taken into account when translating the assets. Please also consider the translation method here

**Comment by JodebaDigitalPulse** [comment]
Hi @HigumaSan4050 , thank you for letting me know. I added a fix to version 2.7.0 or 1.12.0 (Craft 4)
