### ISSUE TITLE
Migration from Typed Link Field to Hyper or Supported Plugin?

### ISSUE THREAD

**Issue by Patchyy** [digitalpulsebe/craft-multi-translator#18]
I've noticed that the linkField is currently used for links, relying on the Typed Link Field plugin. However, Typed Link Field is no longer maintained. Are there plans to transition to Hyper or another actively supported plugin to ensure future compatibility and maintenance?

**Comment by svondervoort** [comment]
This is also holding us back from using this plugin. Any update on a timeline would be great :)
