### ISSUE TITLE
Error with Portuguese language

### ISSUE THREAD

**Issue by tigerchick** [digitalpulsebe/craft-multi-translator#2]
Whenever I try to translate to Portuguese I get the following error:

targetLang="pt" is deprecated, please use "pt-PT" or "pt-BR" instead

In the language setting of the site I have tried selecting "Portuguese", "Portuguese (Portugal)" and "Portuguese (Brazil)" but it makes no difference.
I suspect this may be a problem with the way the language code is in Craft's core but thought I'd check here first.

**Comment by JodebaDigitalPulse** [comment]
Hi @tigerchick, are you using Google or Deepl as a translation service?
