### ISSUE TITLE
Craft 5.3: Entry portability between sections fails

### ISSUE THREAD

**Issue by mersy** [digitalpulsebe/craft-multi-translator#20]
Hi.

I try Craft 5.3.
Entries can be moved between sections on Craft 5.3.
When Multi Translator is enabled, this feature does not work properly. 
I confirmed that entries can be moved when Multi Translator is disabled.

It might be an issue with the CMS, but I would appreciate it if you could look into this.

Thanks.

---

When I check the checkbox, an error appears in the console.
![20240808-042122](https://github.com/user-attachments/assets/8c032959-ec28-492c-9c71-2184eda71fe4)

Nothing happens when I click Move to.
![20240808-042136](https://github.com/user-attachments/assets/ea646920-e57a-42ff-b92e-2a3e6e675cf3)

**Comment by JodebaDigitalPulse** [comment]
Hi, thank you for noticing! I included a fix in 2.7.0.

**Comment by mersy** [comment]
Hi, @JodebaDigitalPulse 
Thank you for quick update.
I moved entries to other section.
