### ISSUE TITLE
Plugin translates all languages to one language

### ISSUE THREAD

**Issue by boboldehampsink** [digitalpulsebe/craft-multi-translator#24]
Hi there,

When using this plugin on a translatable page, and choose, for example, Dutch to English - also the other languages and English itself get translated to English. This happens specifically in a non-translatable matrix block, where the individual fields are translatable. Is this supposed to be?

**Comment by JodebaDigitalPulse** [comment]
Hi

Are you using Craft 4? Is it a default Matrix or Neo? What is the propagation method of the Matrix field?
This is might be related to #23

**Comment by boboldehampsink** [comment]
This is on Craft 4 with Neo. Propagation method is "all"

**Comment by boboldehampsink** [comment]
Looks like the same issue, yes. Can you also update this for 1.x?

**Comment by boboldehampsink** [comment]
Thanks!
