### ISSUE TITLE
Not able to update the glossary name after creation

### ISSUE THREAD

**Issue by pjbaert** [digitalpulsebe/craft-multi-translator#30]
I wanted to update the name of my glossary, but wasn't able to edit it.

![Screenshot 416](https://github.com/user-attachments/assets/9ec95ee1-e08c-44fd-85ce-0969ef9ef5c2)

**Comment by JodebaDigitalPulse** [comment]
Hi @pjbaert , 

This is now possible in the latest releases [2.10.2](https://github.com/digitalpulsebe/craft-multi-translator/releases/tag/2.10.2) for Craft 5 or [1.15.2](https://github.com/digitalpulsebe/craft-multi-translator/releases/tag/1.15.2) for Craft 4 ! 😉
