### ISSUE TITLE
Upload glossary

### ISSUE THREAD

**Issue by pjbaert** [digitalpulsebe/craft-multi-translator#31]
Please consider implementing the 'upload glossary' functionality.

https://support.deepl.com/hc/en-us/articles/360021664739-Uploading-glossaries

**Comment by JodebaDigitalPulse** [comment]
You could do it this way: 

https://github.com/user-attachments/assets/a01842c7-9238-4e22-9910-2ed7d0840b6e

**Comment by pjbaert** [comment]
Thank you! This works perfectly 👌
