### ISSUE TITLE
Add Support for Categories

### ISSUE THREAD

**Issue by remoflury** [digitalpulsebe/craft-multi-translator#32]
Currently, translation for craft's categories are not supported. Can this please be added?

**Comment by WHITE-developer** [comment]
@JodebaDigitalPulse, We are struggling a bit with this as well.

We understand the Categories will be disappearing in the future but are still going to be used for a while in a lot of projects, as they are still supported in Craft 5. 

Hope you can reconsider adding some implementation for this. Thanks in advance anyway 😃.

**Comment by JodebaDigitalPulse** [comment]
Hi @WHITE-developer,

I had cases where Tags and Categories had strange behaviour in Craft 5. And as they are deprecated there was no point in reporting the issues. I think the only reason for them to be available is to allow for easy upgrading old projects.

So, what is keeping you from migrating the elements? There are commands provided to make it easy: read more at https://craftcms.com/blog/entrification and https://github.com/craftcms/cms/pull/12689
