### ISSUE TITLE
FR - Categories

### ISSUE THREAD

**Issue by tigerchick** [digitalpulsebe/craft-multi-translator#4]
Feature request....
It would be extremely useful if categories could also be translated in the same way as entries (sidepanel + bulk).

**Comment by JodebaDigitalPulse** [comment]
Hi there,

We choose not to support anything other than Entries, as the other Element types are disappearing. If you're already on Craft 4 you can adopt "[The Entrification Plan](https://craftcms.com/blog/entrification)" and start converting your Categories. Your application will be more future proof this way as well.

I hope this helps 🙂
