### ISSUE TITLE
FR: Support for ChatGPT?

### ISSUE THREAD

**Issue by nitech** [digitalpulsebe/craft-multi-translator#5]
Will you support ChatGPT?

**Comment by nicholasfoynes** [comment]
HI @nitech, this is indeed on our roadmap for Q2! So stay tuned :) 
More suggestions are always welcome.

**Comment by JodebaDigitalPulse** [comment]
Hi @nitech, you can try the OpenAI API in version 1.6.0 (or 2.1.0 for Craft 5). But it is not as reliable as DeepL or Google Translate, in my experience. But that is in the nature of AI tools I guess.
