### ISSUE TITLE
Craft Commerce support

### ISSUE THREAD

**Issue by JoeriE** [digitalpulsebe/craft-multi-translator#6]
Hi,

First of all, great plugin! Is there any plan to support Craft Commerce products?

Best wishes,
Joeri

**Comment by JodebaDigitalPulse** [comment]
Hi @JoeriE
Great suggestion, I'll look into it!

**Comment by JodebaDigitalPulse** [comment]
Hi @JoeriE, you can update the plugin and start translating products. Please let me know if you encounter any issues.
