### ISSUE TITLE
Plugin support request: ethercreative/seo

### ISSUE THREAD

**Issue by clarknelson** [digitalpulsebe/craft-multi-translator#7]
Any chance you plan to support this plugin? Our client is curious. I may recommend using text from the fields in the meantime. 
https://github.com/ethercreative/seo

**Comment by JodebaDigitalPulse** [comment]
Hi @clarknelson, 
It was not on our planning, but we'll keep it in mind. Indeed, you could use some native fields for now.
Thank you for the suggestion!

**Comment by JodebaDigitalPulse** [comment]
Hi @clarknelson, if you update the plugin to the latest version, you can test this feature.
