### ISSUE TITLE
FR: Support for glossaries with the DeepL API?

### ISSUE THREAD

**Issue by mersy** [digitalpulsebe/craft-multi-translator#9]
Will you support glossaries with the DeepL API?

https://developers.deepl.com/docs/api-reference/glossaries

**Comment by JodebaDigitalPulse** [comment]
hi @mersy,

I did not know this feature yet.

I guess you want to enable the usage of your existing glossaries when translating in the CMS.
Do you think we can achieve this with a new setting to select all the glossaries you want to enable? So they will always be used for each translation.

Managing the glossaries may be too far out of scope for this plugin.

**Comment by mersy** [comment]
Hi, @JodebaDigitalPulse 

Thank you for your comment.

> Managing the glossaries may be too far out of scope for this plugin.

Yes, I feel that managing glossaries will need to be done using the DeepL API in a different way, not through Multi Translator plugin.
For example, managing the glossaries as Craft CMS data and using the DeepL API to handle the glossaries by custom plugin.

---

Since this is also my first time researching this, I don't have a complete understanding of everything.

When you specify a `glossary_id` during translation,it seems that terms from the glossary are prioritized.

![20240514-161330](https://github.com/digitalpulsebe/craft-multi-translator/assets/205165/1160398a-0539-40a6-85fe-c6cfc6b16d15)
https://developers.deepl.com/docs/api-reference/translate

However, it appears that the `glossary_id` is updated each time the glossary is updated, so I think this needs to be considered.

- Retrieve the `glossary_id` based on the `name` of the glossary
- Use that `glossary_id` during translation

This might be the approach to take.

So, there seem to be the following patterns:

- Save the `name` of the glossary in the Multi Translator plugin settings, retrieve the `glossary_id` using the DeepL API, and then translate
- Save the `glossary_id` in the Multi Translator plugin settings and use it for translation

Saving the `name` of the glossary seems to be better for user. 
However, it seems that there might be many patterns, or even multiple patterns, for the combination of `source_lang` and `target_lang`, so it seems difficult to determine the best way to save the settings.

**Comment by JodebaDigitalPulse** [comment]
Thank you, I'll have a look at it, and discuss it with the team. I'll keep you updated. 👍

**Comment by mersy** [comment]
Thank you!!

**Comment by mersy** [comment]
Hi, @JodebaDigitalPulse 

Sounds great!!

I'll try it later.

Thanks
mersy

**Comment by mersy** [comment]
Hi, @JodebaDigitalPulse 

I updated the plugin and tried out the glossary feature. 
I was able to confirm that the terms specified in the glossary are being used in the translation. 

It's great! 
Thank you very much!

**Comment by JodebaDigitalPulse** [comment]
Good, thank you for testing! 😊
